<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OIGE0TE" failures="1" tests="5" name="loginTestWithInValidCredentials" time="25.881" errors="0" timestamp="2019-11-29T16:38:27 IST">
  <testcase classname="tests.login.LoginWithValidCredentials" name="launchingBrowser" time="15.848"/>
  <testcase classname="tests.login.LoginWithValidCredentials" name="validateLogo" time="0.097"/>
  <testcase classname="tests.login.LoginWithValidCredentials" name="validateTitle" time="0.013"/>
  <testcase classname="tests.login.LoginWithValidCredentials" name="validateLogin" time="0.021">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at framework.Repository.getObjectInfo(Repository.java:32)
at framework.Repository.getBy(Repository.java:54)
at tests.login.LoginWithValidCredentials.validateLogin(LoginWithValidCredentials.java:43)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- validateLogin -->
  <testcase classname="tests.login.LoginWithValidCredentials" name="login" time="5.716"/>
</testsuite> <!-- loginTestWithInValidCredentials -->
